### ISSUE TITLE
标题相同的话算作编辑吗？

### ISSUE THREAD

**Issue by caryyu** [LinusLing/WeChatMediaPlatformAutomation#4]
自动化处理重复的数据覆盖问题，所以会和编辑的概念相关。

**Comment by LinusLing** [comment]
我当时只按新建文章的逻辑进行了自动化，并没有编辑功能。
当然也欢迎增加编辑功能的 PR。

**Comment by caryyu** [comment]
好的，明白了，谢谢回复！

**Comment by LinusLing** [comment]
目前的 [1.2.0](https://github.com/LinusLing/WeChatMediaPlatformAutomation/releases/tag/1.2.0) 版本，已经支持修改最近编辑的文章了，详情请见 [changelog](https://github.com/LinusLing/WeChatMediaPlatformAutomation#changelog) 。
