### ISSUE TITLE
选择预览仍旧需要扫描二维码

### ISSUE THREAD

**Issue by woshahua** [LinusLing/WeChatMediaPlatformAutomation#6]
能不能在console抓到二维码的图，然后让用户扫描登陆，不扫码貌似不能登陆

**Comment by LinusLing** [comment]
不管是发布还是预览，都需要先登录，而账号密码的登录方式是一定要管理员扫码的。请仔细阅读 README 中的 [如何使用](https://github.com/LinusLing/WeChatMediaPlatformAutomation#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8)。

至于你说的 “console 抓到二维码的图”，是想表达通过在 console 内显示二维码让管理员扫的意思吗？这和目前直接打开一张图片让管理员扫码的方式相比，貌似并没有更便利。如果我没理解对你的意思，请你详细描述一下，可能是个优化点呢😝
