### ISSUE TITLE
自发发送群发会出现失败的问题

### ISSUE THREAD

**Issue by senglez** [LinusLing/WeChatMediaPlatformAutomation#8]
可以保存预览，但是不能群发成功。ErrorResult显示内容是在群发图文消息界面。

**Comment by LinusLing** [comment]
请提供一下群发时的参数，敏感参数不需要写

**Comment by senglez** [comment]
wechat-format-cli /test.md && wechat-mp-automation -C /test.json
**test.md的内容**
`# 一款自动生成微信公众号文章的软件
~~测试内容~~
++自动采集++
## 黎巴嫩首都贝鲁特发生巨大爆炸11111111

	当地时间8月4日下午6时左右，黎巴嫩首都贝鲁特港口区发生巨大爆炸，多栋房屋受损，玻璃被震碎，天上升起红色烟雾。据黎巴嫩卫生部公布，爆炸造成至少73人死亡，3000人受伤。

　　目前，黎巴嫩官员尚未宣布爆炸原因。有报道称，爆炸是由于化学物质的自燃而导致的，当前现场状况相对稳定，官方没有公布是否有次生灾害的可能性。事件后，以色列方面发布消息，与这一事件无关。（总台记者 孙虎）
`
**test.json的内容**
`{
  "title": "黎巴嫩首都贝鲁特发生巨大爆炸",
  "author": "我爱拍",
  "username": "",
  "password": ""
}
`

**Comment by senglez** [comment]
还出现这个错误，配置文件内容如上：

读取配置文件失败
TypeError: Cannot read property 'split' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/wechat-mp-automation/automation.js:48:53)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

**Comment by LinusLing** [comment]
> wechat-format-cli /test.md && wechat-mp-automation -C /test.json
> **test.md的内容**
> `# 一款自动生成微信公众号文章的软件
> ~测试内容~
> ++自动采集++
> 
> ## 黎巴嫩首都贝鲁特发生巨大爆炸11111111
> ```
> 当地时间8月4日下午6时左右，黎巴嫩首都贝鲁特港口区发生巨大爆炸，多栋房屋受损，玻璃被震碎，天上升起红色烟雾。据黎巴嫩卫生部公布，爆炸造成至少73人死亡，3000人受伤。
> ```
> 
> 　　目前，黎巴嫩官员尚未宣布爆炸原因。有报道称，爆炸是由于化学物质的自燃而导致的，当前现场状况相对稳定，官方没有公布是否有次生灾害的可能性。事件后，以色列方面发布消息，与这一事件无关。（总台记者 孙虎）
> `**test.json的内容**`{
> "title": "黎巴嫩首都贝鲁特发生巨大爆炸",
> "author": "我爱拍",
> "username": "",
> "password": ""
> }
> `

出现这个报错的原因已经查明，是微信公众号后台更新了群发的样式，目前已在最新的 1.3.2 版本修复。详情请见 [changelog](https://github.com/LinusLing/WeChatMediaPlatformAutomation#changelog) 。

wechat-mp-automation@1.3.2

> 还出现这个错误，配置文件内容如上：
> 
> 读取配置文件失败
> TypeError: Cannot read property 'split' of undefined
> at Object. (/usr/local/lib/node_modules/wechat-mp-automation/automation.js:48:53)
> at Module._compile (internal/modules/cjs/loader.js:1158:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
> at Module.load (internal/modules/cjs/loader.js:1002:32)
> at Function.Module._load (internal/modules/cjs/loader.js:901:14)
> at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
> at internal/main/run_main_module.js:18:47

已一并在最新的 1.3.2 版本修复。

wechat-mp-automation@1.3.2

感谢反馈 bug，Thanks♪(･ω･)ﾉ
