### ISSUE TITLE
请问：可以一次发布多个文章吗？

### ISSUE THREAD

**Issue by senglez** [LinusLing/WeChatMediaPlatformAutomation#9]
### 可以发布多个文章吗？
在 md 文件中如何设置？

**Comment by LinusLing** [comment]
不支持一次发布多个文章。

如果有多次发布的需求，可以手动或写一个脚本，替换文章内容和相关参数后多次调用本工具进行预览/发布即可。

**Comment by senglez** [comment]
我的问题表述的不清晰，实际想问的是：一次群发，可以发布多个图文消息吗？公众号一次可以群发8个图文消息，如何在这个工具设置呢？
